# VoxNest 服务器配置文件
server:
  name: VoxNest Server
  version: 1.0.0
  environment: Development
database:
  provider: MySQL
  connection_string: Server=localhost;Database=voxnest;User=root;Password=virgil698;Port=3307;CharSet=utf8mb4;
  enable_sensitive_data_logging: true
  enable_detailed_errors: true
jwt:
  secret_key: 6AvIdDNDxkOdoCbkJ0v4NrFvzCYGdkrUYfuEEKLjpKbsOi2xkkOw1KY7asCJ5ods
  issuer: VoxNest
  audience: VoxNest-Users
  expire_minutes: 1440
cors:
  allowed_origins:
  - http://localhost:54976
  - http://localhost:54977
  - http://localhost:3000
  allowed_methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  allowed_headers:
  - Content-Type
  - Authorization
  - X-Requested-With
logging:
  level: Information
  enable_console: true
  enable_file: true
  file_path: logs/voxnest.log
